# Generated by Django 3.2.9 on 2022-03-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notion',
        ),
    ]
