# Generated by Django 3.2.9 on 2022-03-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_storage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
