# Generated by Django 3.2.9 on 2022-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='namefile',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
