# Generated by Django 3.2.9 on 2022-03-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220320_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFiles',
        ),
    ]
