# Generated by Django 3.2.9 on 2022-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_userfiles_namefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='canedit',
            field=models.BooleanField(default=True),
        ),
    ]
