# Generated by Django 3.2.9 on 2022-03-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userfiles_canedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='filetype',
            field=models.TextField(null=True),
        ),
    ]
