# Generated by Django 3.2.9 on 2022-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userfiles_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='fillformdoc',
            field=models.BooleanField(default=False),
        ),
    ]
